title: "Imad Ahmad"
author: "Imad Ahmad"
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html" title: Home}
  - {file: "README.md" title: Project Portfolio}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:imadahmad97@yahoo.ca"}
  - {title: Github, icon: github, url: "https://github.com/imadahmad97"}
  - {title: LinkedIn, icon: linkedin, url: "linkedin.com/in/imad-ahmad-2aab5a56"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
